In [1]:
## Setup

import boto3
import botocore
import sagemaker
import numpy as np

bucket = 'hackday-training-sagemaker-bucket'
prefix = 'k-nearest-neighbours'
execution_role = sagemaker.get_execution_role()

In [2]:
## Verify training bucket

try:
    boto3.Session().client('s3').head_bucket(Bucket=bucket)
except botocore.exceptions.ParamValidationError as e:
    print('Hey! You either forgot to specify your S3 bucket'
          ' or you gave your bucket an invalid name!')
except botocore.exceptions.ClientError as e:
    if e.response['Error']['Code'] == '403':
        print("Hey! You don't have permission to access the bucket, {}.".format(bucket))
    elif e.response['Error']['Code'] == '404':
        print("Hey! Your bucket, {}, doesn't exist!".format(bucket))
    else:
        raise
else:
    print('Training input/output will be stored in: s3://{}/{}'.format(bucket, prefix))

Training input/output will be stored in: s3://hackday-training-sagemaker-bucket/k-nearest-neighbours


In [3]:
## Load data from result3.csv
import pandas as pd
import io

data_filename = 'result3.csv'

s3_client = boto3.client('s3')

data_response = s3_client.get_object(Bucket=bucket, Key=data_filename)
data_response_body = data_response["Body"].read()

raw_data = pd.read_csv(io.BytesIO(data_response_body), header=0, delimiter=",", low_memory=False)
raw_data.head()

Unnamed: 0  Wine  Water  Saucer  Produce  Light Fixture  Jewelry  Weapon  \
0           0   0.0    0.0     0.0      0.0            0.0      0.0     0.0   
1           1   0.0    0.0     0.0      0.0            0.0      0.0     0.0   
2           2   0.0    0.0     0.0      0.0            0.0      0.0     0.0   
3           3   0.0    0.0     0.0      0.0            0.0      0.0     0.0   
4           4   0.0    0.0     0.0      0.0            0.0      0.0     0.0   

   Powder  File Binder   ...    Bag  Plastic Wrap  Foil  Smoke Pipe  Hot Tub  \
0     0.0          0.0   ...    0.0           0.0   0.0         0.0      0.0   
1     0.0          0.0   ...    0.0           0.0   0.0         0.0      0.0   
2     0.0          0.0   ...    0.0           0.0   0.0         0.0      0.0   
3     0.0          0.0   ...    0.0           0.0   0.0         0.0      0.0   
4     0.0          0.0   ...    0.0           0.0   0.0         0.0      0.0   

   Letterbox  Brick  Sweets  Red Wine  result  
0        0.0    0.0     0.0       0.0       2  
1        0.0    0.0     0.0       0.0       1  
2        0.0    0.0     0.0       0.0       3  
3        0.0    0.0     0.0       0.0       1  
4        0.0    0.0     0.0       0.0       2  

[5 rows x 421 columns]

In [4]:
## Prepare for data splitting

# Shuffle the data
#raw_data = raw_data.sample(frac=1).reset_index(drop=True)

train_size = int(0.9 * raw_data.shape[0])
test_size = raw_data.shape[0] - train_size

print('Training Size: {}'.format(train_size))
print('Testing Size : {}'.format(test_size))

labels = raw_data.get('result').values
features = raw_data.drop(['result', 'Unnamed: 0'], axis=1).values

Training Size: 1121
Testing Size : 125


In [5]:
labels[:5]

array([2, 1, 3, 1, 2])

In [6]:
features[:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
# Split into training and testing
train_features = features[:train_size, :-1]
train_labels = labels[:train_size]
test_features = features[train_size:, :-1]
test_labels = labels[train_size:]

In [8]:
train_features[:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
train_labels[:5]

array([2, 1, 3, 1, 2])

In [10]:
test_features[:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
test_labels[:5]

array([3, 1, 1, 3, 6])

In [12]:
## Upload to S3 (Train Data)
import os
import io
import sagemaker.amazon.common as smac

print('train_features shape = ', train_features.shape)
print('train_labels shape = ', train_labels.shape)

buf = io.BytesIO()
smac.write_numpy_to_dense_tensor(buf, train_features, train_labels)
buf.seek(0)

key = 'hackday-data'

boto3.resource('s3').Bucket(bucket).Object(os.path.join(prefix, 'train', key)).upload_fileobj(buf)
s3_train_data = 's3://{}/{}/train/{}'.format(bucket, prefix, key)
print('uploaded training data location: {}'.format(s3_train_data))


train_features shape =  (1121, 418)
train_labels shape =  (1121,)
uploaded training data location: s3://hackday-training-sagemaker-bucket/k-nearest-neighbours/train/hackday-data


In [13]:
## Upload to S3 (Test Data)
import os
import io
import sagemaker.amazon.common as smac

print('test_features shape = ', test_features.shape)
print('test_labels shape = ', test_labels.shape)

buf = io.BytesIO()
smac.write_numpy_to_dense_tensor(buf, test_features, test_labels)
buf.seek(0)

key = 'hackday-data'

boto3.resource('s3').Bucket(bucket).Object(os.path.join(prefix, 'test', key)).upload_fileobj(buf)
s3_test_data = 's3://{}/{}/test/{}'.format(bucket, prefix, key)
print('uploaded test data location: {}'.format(s3_test_data))

test_features shape =  (125, 418)
test_labels shape =  (125,)
uploaded test data location: s3://hackday-training-sagemaker-bucket/k-nearest-neighbours/test/hackday-data


In [14]:
## Training


import matplotlib.pyplot as plt

import sagemaker
from sagemaker import get_execution_role
from sagemaker.predictor import csv_serializer, json_deserializer
from sagemaker.amazon.amazon_estimator import get_image_uri


def trained_estimator_from_hyperparams(s3_train_data, hyperparams, output_path, s3_test_data=None):
    """
    Create an Estimator from the given hyperparams, fit to training data, 
    and return a deployed predictor
    
    """
    # set up the estimator
    knn = sagemaker.estimator.Estimator(get_image_uri(boto3.Session().region_name, "knn"),
        get_execution_role(),
        train_instance_count=1,
        train_instance_type='ml.m4.xlarge',
        output_path=output_path,
        sagemaker_session=sagemaker.Session())
    knn.set_hyperparameters(**hyperparams)
    
    # train a model. fit_input contains the locations of the train and test data
    fit_input = {'train': s3_train_data}
    if s3_test_data is not None:
        fit_input['test'] = s3_test_data
    knn.fit(fit_input)
    return knn

In [15]:
hyperparams = {
    'feature_dim': 418,
    'k': 6,
    'sample_size': 1000,
    'predictor_type': 'classifier' 
}
output_path = 's3://' + bucket + '/' + prefix + '/default_example/output'
knn_estimator = trained_estimator_from_hyperparams(s3_train_data, hyperparams, output_path, 
                                                   s3_test_data=s3_test_data)

INFO:sagemaker:Creating training-job with name: knn-2019-03-11-03-50-44-586


2019-03-11 03:50:44 Starting - Starting the training job...
2019-03-11 03:50:46 Starting - Launching requested ML instances............
2019-03-11 03:52:50 Starting - Preparing the instances for training...
2019-03-11 03:53:38 Downloading - Downloading input data
2019-03-11 03:53:38 Training - Downloading the training image.....
Docker entrypoint called with argument(s): train
[03/11/2019 03:54:28 INFO 139639433545536] Reading default configuration from /opt/amazon/lib/python2.7/site-packages/algorithm/resources/default-conf.json: {u'index_metric': u'L2', u'_tuning_objective_metric': u'', u'_num_gpus': u'auto', u'_log_level': u'info', u'faiss_index_ivf_nlists': u'auto', u'epochs': u'1', u'index_type': u'faiss.Flat', u'_faiss_index_nprobe': u'5', u'_kvstore': u'dist_async', u'_num_kv_servers': u'1', u'mini_batch_size': u'5000'}
[03/11/2019 03:54:28 INFO 139639433545536] Reading provided configuration from /opt/ml/input/config/hyperparameters.json: {u'sample_size': u'1000', u'feature_dim


2019-03-11 03:54:38 Uploading - Uploading generated training model
2019-03-11 03:54:38 Completed - Training job completed
Billable seconds: 72


In [16]:
## Deploy Endpoint

knn_inference = knn_estimator.deploy(
    initial_instance_count=1,
    instance_type='ml.m4.xlarge',
)

print('Endpoint name: {}'.format(knn_inference.endpoint))

INFO:sagemaker:Creating model with name: knn-2019-03-11-03-54-56-688
INFO:sagemaker:Creating endpoint with name knn-2019-03-11-03-50-44-586


---------------------------------------------------------------------------!Endpoint name: knn-2019-03-11-03-50-44-586


In [17]:
## Making predictions
import time

knn_inference.content_type = 'text/csv'
knn_inference.serializer = csv_serializer
knn_inference.accept = 'application/json'
knn_inference.deserializer = json_deserializer

batches = np.array_split(test_features, 100)
print('data split into 100 batches, of size %d.' % batches[0].shape[0])

# obtain an np array with the predictions for the entire test set
start_time = time.time()
predictions = []
for batch in batches:
    print(batch)
    result = knn_inference.predict(batch)
    cur_predictions = np.array([result['predictions'][i]['predicted_label'] for i in range(len(result['predictions']))])
    predictions.append(cur_predictions)
predictions = np.concatenate(predictions)
run_time = time.time() - start_time

test_size = test_labels.shape[0]
num_correct = sum(predictions == test_labels)
accuracy = num_correct / float(test_size)
print('time required for predicting %d data point: %.2f seconds' % (test_size, run_time))
print('accuracy of model: %.1f%%' % (accuracy * 100) )


data split into 100 batches, of size 2.
[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.       

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.     

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.         98.57164764
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
  81.20116425  0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
  

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.         92.04468536
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
  92.04468536  0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
  

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.     

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
  83.75082397  0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.     

[[94.22917175  0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
  73.70088196  0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.     

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.         86.27887726
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.         99.69953918
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.       

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.     

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.     

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.         89.14587402  0.          0.          0.
   0.          0.          0.          0.          0.         85.61819458
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
  

In [18]:
## Delete Endpoint

sagemaker.Session().delete_endpoint(knn_inference.endpoint)

INFO:sagemaker:Deleting endpoint with name: knn-2019-03-11-01-05-21-757


In [18]:
# Test lambda code
sagemakerPayloadStr = '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,94.76896667480469,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,97.7795639038086,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,94.7276382446289,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0'

clientSM = boto3.client('sagemaker-runtime')
        
responseSageMaker = clientSM.invoke_endpoint(
    EndpointName='knn-2019-03-11-03-50-44-586',
    ContentType='text/csv',
    Body=sagemakerPayloadStr
)

responseSageMaker

{'ResponseMetadata': {'RequestId': '70359aef-991d-4fd4-ab9b-10150c90e425',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '70359aef-991d-4fd4-ab9b-10150c90e425',
   'x-amzn-invoked-production-variant': 'AllTraffic',
   'date': 'Mon, 11 Mar 2019 12:40:50 GMT',
   'content-type': 'application/json',
   'content-length': '43'},
  'RetryAttempts': 0},
 'ContentType': 'application/json',
 'InvokedProductionVariant': 'AllTraffic',
 'Body': <botocore.response.StreamingBody at 0x7fec4be3f898>}

In [20]:
import json

sageresult = json.loads(responseSageMaker['Body'].read().decode())
sageresult

{'predictions': [{'predicted_label': 1.0}]}